name: trip_app
description: A new Flutter project

publish_to: 'none' # Remove essa linha se você estiver publicando o pacote

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - imagens/lake.jpeg
    - imagens/cristo.jpeg
    - imagens/coliseu.jpeg
    - imagens/chichen.jpeg
    - imagens/machu.jpeg

